/**************************************/
/*                                    */
/* SYSVALPRG - Display systems value  */
/*                                    */
/* Coded by: Mauricio Gomes de Barros */
/*                                    */
/* Student ID: 122509227              */
/*                                    */
/* SIGNATURE ________________________ */
/**************************************/

DSPLIBL
EDTLIBL
DSPLIBL
DSPSYSVAL QSYSLIBL
DSPSYSVAL QUSRLIBL
DSPSYSVAL QMODEL 